### ISSUE TITLE
Read my mind

### ISSUE THREAD

**Issue by bahmutov** [soup-js/soup-js#11]
You guys read my mind! I just published the blog post about passing streams from parent to child component https://glebbahmutov.com/blog/why-use-reactive-streams-for-components/ and you lib implements it nicely. I need to list you as a better match for the idea than MobX

**Comment by wdavew** [comment]
Thanks! Just read your post and it gave us a few ideas of where to go next. But yeah -- the approach you suggest is definitely what we're trying to do here. Also, I do try to follow your blog and it's been very helpful over the past few months -- great resource for functional and reactive programming in jasvascript.

**Comment by bahmutov** [comment]
Thanks @wdavew ! Hope I can help in any kind, will follow your progress, best of luck.
